### ISSUE TITLE
P03 - Get your socks on

### ISSUE THREAD

**Issue by joerez** [MakeSchool-Tutorials/Make-Chat-Tutorial#2]
Right before the take it to the front section the following needs to be added:

Tell them to node app.js or nodemon or whatever.
Because we named our main file app.js we need to add the following to our package.json file:
	
	```js
	...
	 "main": "app.js",
 	 "scripts": {
   	 "start": "node app.js",
  	  "test": "echo \"Error: no test specified\" && exit 1"
 	 },
	...
	```

Right before the great but what happened:

Trying to run my code gives me weird errors.
```
Cannot find module '/Users/x/index.js'
```

Not sure what’s wrong with my code.

**Comment by ibirnam** [comment]
solved this by fixing package.json in the Getting Started chapter.
