### ISSUE TITLE
Displaying Online Users, Content Clarity

### ISSUE THREAD

**Issue by AwesomeZaidi** [MakeSchool-Tutorials/Make-Chat-Tutorial#4]
Amazing tutorial! One small piece of feedback for anyone that doesn't know CSS very well, page 5 -  Start Chat, Making it look like Slack, there could be one sentence added that would save students some headache time. Only saying this because I've seen a few students scratching their heads about this.. moving forward and then saying something like, 'yeah once you continue, it gets fixed for some reason'.

When you first go through adding the new HTML, CSS then reload your browser, you almost assume you did something wrong because none of the new UI is displaying.

There should be a friendly note in the content right after you add your CSS - 'Load the page and notice none of the new UI will show just yet because as of default we've set the `.mainContainer` style to `display: none`. In the next step, we use jQuery to modify the DOM and display our new cool UI!'

**Comment by ibirnam** [comment]
Great feedback @AwesomeZaidi ! Fixed now in 0b2e329f0a7dc28c841273db8b432a14118d596d, will be live soon!
