### ISSUE TITLE
Wrong relative path for index.js

### ISSUE THREAD

**Issue by natepill** [MakeSchool-Tutorials/Make-Chat-Tutorial#5]
On page 6 of the tutorial, underneath the subtitle:
Finally go back to your client, to show the users on the page.

The relative path should be /public/index.js and **NOT** /views/index.js

Page 6 of the tutorial:
https://www.makeschool.com/academy/track/make-chat/make-chat/saving-and-destroying-users

**Comment by ibirnam** [comment]
Great catch! Fixed in 2b9ee683c79107cc63a55d9ce3bba7e4e228a971
