### ISSUE TITLE
6. Saving and Destroying Users

### ISSUE THREAD

**Issue by nsafai** [MakeSchool-Tutorials/Make-Chat-Tutorial#8]
`let onlineUsers = {}` needs to be declared at the top of app.js and outside of the `io.on('connection, [...])` function.

Otherwise, onlineUsers will not persist.

Before:
```
// app.js

const io = require('socket.io')(server);
io.on("connection", (socket) => {
  let onlineUsers = {};
  require('./sockets/chat.js')(io, socket, onlineUsers);
})
```

After:
```
// app.js

let onlineUsers = {};

// Socket.io
let io = require('socket.io').listen(server);
io.on('connection', (socket) => {
  require('./sockets/chat.js')(io, socket, onlineUsers);
});
```

**Comment by ibirnam** [comment]
@nsafai I'm not sure I'm following what you're saying. You say that `onlineUsers` needs to be declared outside of the `io.on('connection, [...])` function, but in both the _before_ and _after_ blocks you have, `onlineUsers` is declared outside of that function in both, just the line numbers have switched.

I also currently have my solution implemented as you have in the _before_ block and i have `onlineUsers` persisting throughout a given session.

**Comment by nsafai** [comment]
hmm, maybe i read the directions wrong, as the instructions in the tutorial look correct now! Thanks!
