### ISSUE TITLE
5. Start Chatting

### ISSUE THREAD

**Issue by campbellmarianna** [MakeSchool-Tutorials/Make-Chat-Tutorial#9]
In the first section, code for the index.css file has CSS rules that are formatted differently:
```
.usernameForm{
  display: flex;
  width : 50%;
  margin-left: auto;
  margin-right: auto;
  padding: 10px;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}
```
[The Airbnb CSS Style Guide has a recommended format](https://github.com/airbnb/css#formatting):
```
.avatar {
  border-radius: 50%;
  border: 2px solid white;
}
```

**Comment by ibirnam** [comment]
@campbellmarianna - great suggestion! Given updating that would be a big change across multiple chapters, I'm going to wait until the end of the term to push changes. I just wanted to let you know I saw your feedback though, and will update it once term 4 ends!

**Comment by campbellmarianna** [comment]
Okay! Thank you for letting me know.

**Comment by ibirnam** [comment]
@campbellmarianna - changes have now been pushed! I followed the syntax as best I could without introducing major changes to the tutorial (will have to be part of a larger revamp we do later). But I encourage you to take a look, and if you have suggestions on ways to improve it (or have a stylesheet of your own you like better) please share it with me, and we can see if we can figure out a way to integrate it! Always looking for student innovations!
